package school.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import school.Student;
import school.Teacher;

import school.Middle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MIDDLE".
*/
public class MiddleDao extends AbstractDao<Middle, Long> {

    public static final String TABLENAME = "MIDDLE";

    /**
     * Properties of entity Middle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MiddleStudentId = new Property(1, long.class, "MiddleStudentId", false, "MIDDLE_STUDENT_ID");
        public final static Property MiddleTeacherId = new Property(2, long.class, "MiddleTeacherId", false, "MIDDLE_TEACHER_ID");
    };

    private DaoSession daoSession;

    private Query<Middle> student_MiddleListQuery;
    private Query<Middle> teacher_MiddleListQuery;

    public MiddleDao(DaoConfig config) {
        super(config);
    }
    
    public MiddleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MIDDLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MIDDLE_STUDENT_ID\" INTEGER NOT NULL ," + // 1: MiddleStudentId
                "\"MIDDLE_TEACHER_ID\" INTEGER NOT NULL );"); // 2: MiddleTeacherId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MIDDLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Middle entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMiddleStudentId());
        stmt.bindLong(3, entity.getMiddleTeacherId());
    }

    @Override
    protected void attachEntity(Middle entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Middle readEntity(Cursor cursor, int offset) {
        Middle entity = new Middle( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // MiddleStudentId
            cursor.getLong(offset + 2) // MiddleTeacherId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Middle entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMiddleStudentId(cursor.getLong(offset + 1));
        entity.setMiddleTeacherId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Middle entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Middle entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "middleList" to-many relationship of Student. */
    public List<Middle> _queryStudent_MiddleList(long MiddleStudentId) {
        synchronized (this) {
            if (student_MiddleListQuery == null) {
                QueryBuilder<Middle> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MiddleStudentId.eq(null));
                student_MiddleListQuery = queryBuilder.build();
            }
        }
        Query<Middle> query = student_MiddleListQuery.forCurrentThread();
        query.setParameter(0, MiddleStudentId);
        return query.list();
    }

    /** Internal query to resolve the "middleList" to-many relationship of Teacher. */
    public List<Middle> _queryTeacher_MiddleList(long MiddleTeacherId) {
        synchronized (this) {
            if (teacher_MiddleListQuery == null) {
                QueryBuilder<Middle> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MiddleTeacherId.eq(null));
                teacher_MiddleListQuery = queryBuilder.build();
            }
        }
        Query<Middle> query = teacher_MiddleListQuery.forCurrentThread();
        query.setParameter(0, MiddleTeacherId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getStudentDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTeacherDao().getAllColumns());
            builder.append(" FROM MIDDLE T");
            builder.append(" LEFT JOIN STUDENT T0 ON T.\"MIDDLE_STUDENT_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN TEACHER T1 ON T.\"MIDDLE_TEACHER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Middle loadCurrentDeep(Cursor cursor, boolean lock) {
        Middle entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Student student = loadCurrentOther(daoSession.getStudentDao(), cursor, offset);
         if(student != null) {
            entity.setStudent(student);
        }
        offset += daoSession.getStudentDao().getAllColumns().length;

        Teacher teacher = loadCurrentOther(daoSession.getTeacherDao(), cursor, offset);
         if(teacher != null) {
            entity.setTeacher(teacher);
        }

        return entity;    
    }

    public Middle loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Middle> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Middle> list = new ArrayList<Middle>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Middle> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Middle> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
